# Inserts a blank line between shell prompts
add_newline = true 

# Custom format
format = """
[â”Œâ”€â”€â”€â¤™](green bold) $all
[â”‚](green bold)
[â””â”€â†’](green bold) """

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
disabled = true
#success_symbol = "[âœ](green)"

[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

# Username config
[username]
show_always = true
style_user = "blue bold"
style_root = "red bold"
format = "[$user]($style)"

# Hostname config
[hostname]
ssh_only = false
format = " @ [$hostname](green bold) in "
disabled = false

# Dir config
[directory]
truncation_length = 3
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " ğŸ”’"

